/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_zhangniuniu_jnidemo_JniUtil */

#ifndef _Included_test_zhangniuniu_jnidemo_JniUtil
#define _Included_test_zhangniuniu_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_zhangniuniu_jnidemo_JniUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_zhangniuniu_jnidemo_JniUtil_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     test_zhangniuniu_jnidemo_JniUtil
 * Method:    getLenthStrFromNative
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_test_zhangniuniu_jnidemo_JniUtil_getLenthStrFromNative
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
